---
title: "Final Report"
author: "yuyi"
date: "2017年2月5日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 簡介
本報告以Kaggle 的 Titanic 訓練與測試來進行資料整理

##資料讀取
讀取“https://storage.googleapis.com/r_rookies/kaggle_titanic_train.csv” 資料，命名為titanic

```{r titanic}
titanic <- read.csv("https://storage.googleapis.com/r_rookies/kaggle_titanic_train.csv", stringsAsFactors = FALSE)
```
##資料外框與敘述統計

使用 str() 函數得知這個資料有 891 個觀測值與 12 個變數。
```{r str}
str(titanic)
```
使用 summary() 函數進行敘述性統計,發現 Age 變數有 177 個NA值。
```{r summary}
summary(titanic)
```
##資料清理
針對Age的NA值,用平均數進行填補。
```{r mean,summary}
age_mean <- mean(titanic$Age, na.rm = TRUE)
titanic$Age[is.na(titanic$Age)] <- age_mean
summary(titanic$Age)
```
##探索性分析
利用 ggplot2 與 plotly套件,將Titanic的資料彙整成圖，觀察性別、年紀與社經地位
```{r }
library(ggplot2)
library(plotly)
T1<-ggplot(titanic, aes(Pclass)) + 
geom_bar(aes(fill = Sex))+ 
ggtitle(" Pclasses   vs   sexes")
ggplotly(T1)
```

```{r }
T2<-ggplot(titanic, aes(x = Age)) +
  geom_histogram(aes(fill = Sex))+
  ggtitle("Ages vs sexes")
ggplotly(T2)
```






